name: deploy
on:
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: deploy via ssh
              uses: appleboy/ssh-action@master
              with:
                  key: ${{ secrets.SSH_KEY }}
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.REMOTE_PATH }}
                      git pull
                      ~/.local/bin/uv venv
                      source .venv/bin/activate
                      ~/.local/bin/uv sync
