name: Lint with Ruff
on:
    push:
        branches:
            - master

jobs:
    ruff:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: astral-sh/ruff-action@main
              with:
                  version: 0.12.0
                  args: check --select E,F,I --output-format github
                  src: "./src"

